kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: wildfly
  SourceLocation: target/dmit2015-assignment04-nmorrish1.war
  SourceType: binary
  Ports:
  - 8080/TCP
  - 8778/TCP
  Application: app
  Project: default
  Name: assignment04-nmorrish1
  Url:
  - Name: assignment04-nmorrish1-8080
    Port: 8080
  - Name: assignment04-nmorrish1-8778
    Port: 8778
